### PR TITLE
add SourceLink support to the library

### PR DESCRIPTION
**Pull request by marfenij**
Hi again )
This is other awesome stuff which must present in each library IMHO.

I'm not familiar with codecov.io, but think this change should not break anything

### CODE REVIEW

**Comment by marfenij** [comment]
Hi @dotarj 
any notes for that PR ?

**Comment by marfenij** [comment]
I embedded PDB not used in runtime, it used for debug purpose.

That author of SourceLink write on [Github](https://github.com/dotnet/core/blob/master/Documentation/diagnostics/source_link.md#tooling)

about VS Code:
* OmniSharp plugin (https://github.com/OmniSharp/omnisharp-vscode/issues/373#issuecomment-368663495)

about Rider:
* I can't find any proof that this feature supported by it, but R# and .Peek allow to used that - mb Rider also support... I don't use Rider so can't check that

**Comment by dotarj** [comment]
Hi @marfenij, I've had some trouble building protobuf-net-data when source link was enabled. Apparently, source link uses the command 'git rev-parse --show-toplevel' which failed because my machine was badly configured. That's resolved and everything looks good. One question though: shouldn't the argument -p:IncludeSymbols=true be removed for the msbuild -t:pack command?

**Comment by marfenij** [comment]
@dotarj hi. I think need remove msbuild parameter, but I need also resolve conficts

**Comment by dotarj** [comment]
Ok, if you remove the argument, I'll resolve the conflicts. :smiley:

**Comment by marfenij** [comment]
@dotarj  these conflicts is not deadly, let's try check if you fix appveyor script

**Comment by dotarj** [comment]
All systems go! 😄 Only the -p:IncludeSymbols=true argument still has to be removed, but I'll do that in another commit. Thanks for the contribution!

**Comment by marfenij** [comment]
@dotarj  I stuck with internet and can't build solution - nuget can't restored

But you do it ))))

**Pull request merged**
