### PR TITLE
Net core support

### PR DESCRIPTION
**Pull request by marfenij**
Hi. It's a try to extend your library to support netstandard2.0 framework 
I made this as separate sln and projects. Source files for library not changed (except one bug fixed when copying stream)
For tests source I'd copy cause they need changes, after upgrade/replace test framework.

For completing need delete old staff and leave new sln and projects (I don't do that cause that merge can be reviewed)

### CODE REVIEW

**Comment by dotarj** [comment]
Hi @marfenij, thank you for your pull request. I recently started picking up development of protobuf-net-data and the first thing I wanted to do is make it support .NET standard. I took a different approach by using the new csproj format. This way I didn't have to add another csproj, but delete all existing csproj's and create a one new csproj with multiple target frameworks. I didn't merge it to master yet, but you can see the changes in pull request #37.

**Comment by marfenij** [comment]
@dotarj  I use another sln for review only, so you feel free delete old stuff and use new sln 

P.S so you new maintainer/owner for protobuf-net-data?

**Comment by dotarj** [comment]
Yes, we've agreed that I take over maintenance of protobuf-net-data.

**Comment by dotarj** [comment]
Hi @marfenij, would you be willing to create a new pull request with your bug fixes?

**Comment by marfenij** [comment]
@dotarj yes I do it ASAP

**Pull request closed without merging**
